import 'package:flutter/material.dart';

/// TEMPLATE — generated by `appstoresuite init`, not wired up on its own.
/// Debug-only routes for `<scheme>://shot/<id>?lang=<code>` deep links, driven
/// by `appstoresuite auto-capture` (see app_store_suite.yaml's `shots:`).
/// Flutter's engine auto-dispatches deep links as named routes — for
/// `<scheme>://shot/home` that arrives here as route "/home" (the "shot" host
/// segment is not part of the path). Each route below should land directly on
/// a target screen with sample/mock data already in place — no login, no live
/// network calls — see README's "Auto-capture requirements" section.
///
/// TO USE THIS TEMPLATE:
///
/// 1. Register your URL scheme (iOS: CFBundleURLTypes in Info.plist; Android:
///    an intent-filter with android:scheme="<scheme>" on the launcher
///    activity) — see README's "Auto-capture requirements".
///
/// 2. Set app.deep_link_scheme and shots: in app_store_suite.yaml to match
///    the cases you add below.
///
/// 3. Replace every `TODO` below with real screens/sample data from your app.
///    Keep each case dead simple: build the screen straight from in-memory
///    sample data, nothing conditional on real app state.
///
/// 4. Wire this into your MaterialApp, gated to debug builds only — this
///    must never ship in a release build:
///
///      import 'package:flutter/foundation.dart' show kDebugMode;
///      // ...
///      MaterialApp(
///        // ... your existing home / other MaterialApp params, unchanged ...
///        onGenerateRoute: kDebugMode ? ScreenshotRouter.onGenerateRoute : null,
///      )
///
///    `onGenerateRoute` and `home` coexist fine — `home` still serves route
///    "/", this only handles routes that don't match.
///
/// 5. GOTCHA — splash screen races: if your app has a splash/bootstrap screen
///    that navigates away on its own after some delay (auth check, etc.),
///    make sure it doesn't unconditionally clobber a route that's already
///    been pushed on top of it by this router. A deep link can arrive and
///    get routed *while* your splash screen's own timer is still pending —
///    if splash then unconditionally calls
///    `Navigator.of(context).pushReplacement(...)`, that replaces whatever's
///    currently on top (possibly this router's screen, not splash itself),
///    clobbering it. Guard it:
///
///      final route = ModalRoute.of(context);
///      if (route != null && !route.isCurrent) return; // something already navigated on top — don't clobber it
///      Navigator.of(context).pushReplacement(...);
///
/// 6. GOTCHA — network images: if a shot's screen shows real network images
///    (e.g. sample data with photo URLs), a capture can fire before they've
///    finished loading, showing broken-image placeholders instead. The
///    simplest fix is a generous --render-delay (`appstoresuite auto-capture
///    --render-delay 6`, or higher). If that's still flaky (seen in practice
///    on Android emulators — concurrent requests against the emulator's
///    virtual network can silently drop one), precache sequentially with one
///    retry each before showing the screen — see `_Prepared`'s doc comment
///    below for how to pass a BuildContext into `prepare` for this.
///
/// 7. iOS-only gotcha — you may see a one-time "Open in <App>?" system
///    dialog the first time a capture run opens a deep link; auto-capture
///    itself detects this and pauses with instructions to tap Open, so
///    nothing you need to build here.
class ScreenshotRouter {
  static Route<void>? onGenerateRoute(RouteSettings settings) {
    if (settings.name == null) return null;
    final uri = Uri.parse(settings.name!);
    final lang = uri.queryParameters['lang'];

    switch (uri.path) {
      // TODO: replace with your own shot ids/screens. One case per `shots:`
      // entry in app_store_suite.yaml, e.g. for
      //   shots:
      //     - id: home
      //       route: shot/home
      // this handles "/home":
      case '/home':
        return MaterialPageRoute(
          builder: (context) => _Prepared(
            prepare: () => _applyLocale(lang),
            // TODO: replace with your actual home screen + sample data.
            child: const Placeholder(),
          ),
        );
      default:
        return null;
    }
  }

  /// TODO: replace with your app's own locale-switching service. This lets
  /// one running app instance capture every configured language back to
  /// back (`auto-capture --lang en,el`) without an OS locale change or
  /// reinstall — the app just needs some `LocaleService.setLocale(...)`
  /// equivalent that MaterialApp's `locale:` listens to.
  static Future<void> _applyLocale(String? lang) async {
    if (lang == null) return;
    // setLocale() typically notifies listeners synchronously; called
    // straight from _Prepared's lazily-built future, that can land mid-build
    // and throw ("setState() called during build"). Yield one frame first so
    // it runs after the current build finishes.
    await Future<void>.delayed(Duration.zero);
    // TODO: e.g. await LocaleService.instance.setLocale(Locale(lang));
  }
}

/// Runs [prepare] exactly once (cached in [State], not rebuilt on every
/// build), then shows [child]. [prepare] may trigger a locale change that
/// notifies listeners and rebuilds this widget's ancestors — calling
/// [prepare] again on every build would re-trigger that and loop.
///
/// If you need a BuildContext inside `prepare` (e.g. for `precacheImage`,
/// see gotcha #6 above), change the signature to
/// `Future<void> Function(BuildContext)` and call `widget.prepare(context)`
/// in `_PreparedState` below instead.
class _Prepared extends StatefulWidget {
  const _Prepared({required this.prepare, required this.child});

  final Future<void> Function() prepare;
  final Widget child;

  @override
  State<_Prepared> createState() => _PreparedState();
}

class _PreparedState extends State<_Prepared> {
  late final Future<void> _future = widget.prepare();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<void>(
      future: _future,
      builder: (context, snapshot) {
        if (snapshot.connectionState != ConnectionState.done) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        return widget.child;
      },
    );
  }
}